dataSale <- read.csv("D:/PG-DBDA CDAC/R/Day2/data/sales_data.csv")
View(dataSale)


dataSale %>%
  group_by(Country) %>%
  summarize(m=mean(Revenue),
            n=n())

# bike demand is greater in which country 
dataSale %>%
  group_by(Country) %>%
  filter(Product_Category=='Bikes') %>%
  summarize(count=n())%>%
  ungroup()

unique(dataSale)

dataSale %>%
  filter(Product_Category == "Bike") %>%
  group_by(Country, Sub_Category)%>%
  summarize(count=n())%>%
ungroup()

#Find how out number of accessories used by each age group in each country?

dataSale %>%
  filter(Product_Category=='Accessories')%>%
  group_by(Country,Age_Group)%>%
  summarize(ab=sum(Order_Quantity))
  ungroup()


dataSale %>%
    group_by(Product_Category,Country,Age_Group)%>%
    summarize(ab=sum(Order_Quantity))
  ungroup()
  
    
  # for multiline comment ctrl+shift+c
#Find out preference on accessories based on gender in different country
  
  dataSale%>%
    filter(Product_Category=='Accessories')%>%
    group_by(Country,Customer_Gender)%>%
    summarize(count=n())
  ungroup()
  

#Find out unit cost greater then average cost for the month of April of Australia
  
  dataSale%>%
    filter(Country=='Australia' & Month=='April' & Unit_Cost>mean(Cost))
    

#Most popular product by order_quantity

  dataSale%>%
    group_by(Product)%>%
    summarize(popular=sum(Order_Quantity))%>%
    arrange(desc(popular))
  
  
#Find the total profit generated by mountain bike in UNited states in the year in 2013

  dataSale%>%
    filter(Country=='United States' & Year=='2013' & Sub_Category=='Mountain Bikes')%>%
    summarise(Totalprofit=sum(Profit))

# How many females are buying product_category,every year to show to growth
  
  dataSale%>%
    filter(Customer_Gender=='F')%>%
    group_by(Country,Product_Category,Year)%>%
    summarize(total=sum(Order_Quantity))
  
# Barplot #Scatter plot #Pie chart # histogram #line chart